# Generated by Django 4.2.6 on 2023-10-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPage",
            new_name="BlogIndexPage",
        ),
        migrations.RenameField(
            model_name="blogindexpage",
            old_name="body",
            new_name="intro",
        ),
    ]
